name: Build and Test

on:
    push:
      branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake build-essential
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
    
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ..
    
    - name: Build
      run: |
        cd build
        make
    
    - name: Test
      run: |
        cd build
        ctest --verbose