name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Install general dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Install SFML
      uses: oprypin/install-sfml@v1.4
      with:
        sfml-version: 2.6.1

    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure
      run: |
        cd build
        cmake .. -DBUILD_TESTS=ON
      
    - name: Build
      run: |
        cd build
        make
      
    - name: Test
      run: |
        cd build
        ctest --verbose